### ISSUE TITLE
difference between in 0-in-1 and 0-cv-1

### ISSUE THREAD

**Issue by hampa** [ctag-fh-kiel/ctag-tbd#13]
Hi,

I'm using TBD as a sound generator and want to use 0-in-1 for additional control of the module.

What is the difference between the inputs? Can they be used in the same way?

**Comment by ctag-fh-kiel** [comment]
0-in-1 are audio inputs @44.1kHz sampling rate
0-cv-1 are control voltage inputs @44.1kHz / 32 sampling rate
existing plugins use only cv for modulation
but in principle you can also use the audio ins for modulation at audio
rate when you program your own ones

**Comment by hampa** [comment]
Cool. I’ll give it a try.

I assume making the audio inputs into outputs is not possible?

**Comment by ctag-fh-kiel** [comment]
Correct, but you can play with the pins of the codec and the codec setting
in software, many of the codec's features are not used yet, e.g. EQ,
microphone in, compressor, speaker out, headphones out etc.
This is the data sheet https://cirrus.com/products/wm8978/

**Comment by hampa** [comment]
Hi,

I’m trying to output CV messages from them audio outputs.

What voltage would output if I put -1, 0 or 1 in the code? I don’t have a proper voltage measuring module so I’m trying to figure it out using pitch.

-1 becomes -5 volt
0 becomes 0 volt
1 becomes 5 volt

Is that correct?

**Comment by ctag-fh-kiel** [comment]
That depends if you have configured your CV input to uni or bi-polar (Configuration Menu). In uni, range is 0..1 (0..5V) in bi, range is -1..1 (-5..5V). Details are in Calibration.cpp line 230++
