### ISSUE TITLE
building on osx catalina

### ISSUE THREAD

**Issue by hampa** [ctag-fh-kiel/ctag-tbd#2]
I'm unable to build the simulator.

I have boost 1.74 installed.

I've attached the build output. Seems to be some ASIO icompatibility.
[ctag-build.txt](https://github.com/ctag-fh-kiel/ctag-tbd/files/5475426/ctag-build.txt)

**Comment by ctag-fh-kiel** [comment]
Boost version Boost 1.53.0 is required in the CMakeLists.txt file, however, I don't see why is should not work with 1.74.

Have you tried "brew install boost"?

**Comment by ctag-fh-kiel** [comment]
In fact, I am on Boost 1.73.0

**Comment by hampa** [comment]
Yes, brew install boost is how I installed it. It is up to date.

https://gitlab.com/eidheim/Simple-Web-Server

This version of Simple-Web-Server compiles, it has some updates to the ASIO code. When I compile the Simple-Web-Server in ctag I get the same ASIO errors.

**Comment by ctag-fh-kiel** [comment]
Yes, I was able to reproduce the issue. With the latest Boost libs eidheim/Simple-Web-Server needed to be updated.
Please check if it works for you now from TBD master branch and comment.

Thanks for reporting the issue...

**Comment by hampa** [comment]
It works now. Thanks :)
