### ISSUE TITLE
TBD plugin "FBDlyLine" has Dry/Wet slider on the GUI, but it seems to be not implemented yet in the source-code?

### ISSUE THREAD

**Issue by Visuelle-Musik** [ctag-fh-kiel/ctag-tbd#20]
Hi Robert,
maybe I'm missing something, but it looks like there is a piece of code missing from "ctagSoundProcessorFBDlyLine.cpp", below is what I found:

From "mui-FBDlyLine.jsn":
{"id":"drywet","name":"Dry / Wet","type":"int","min":0,"max":4095,"step":1}

From "ctagSoundProcessorFBDlyLine.cpp":
    fDryWet = (float) drywet / 4095.f;
    for (uint32_t i = 0; i < bufSz; i++) {
        data.buf[i * 2 + processCh] *= fLevel;

all the best,
Mathias

**Comment by ctag-fh-kiel** [comment]
Fixed with 0.9.16
