### ISSUE TITLE
Feature request: double-click to mute / center GUI-elements of TBD by setting int-values to zero then...

### ISSUE THREAD

**Issue by Visuelle-Musik** [ctag-fh-kiel/ctag-tbd#21]
Hi Robert,
it would be great if it were possible some day for the TBD to set a numeric value to 0 by double-clicking the element on the GUI.

-> For values from 0 to x this would mute the level / put the slider all way to the left, example:
{"id":"ResonanceModulationAmount","name":"Resonance Modulation Level","type":"int","min":0,"max":4095,"step":1},

-> For values from -x to y this would center the level /  put the slide to the center, example:
{"id":"FilterTracking","name":"Filter key tracking (Pitch-CV to Cutoff)","type":"int","min": -2048,"max": 2047,"step": 1},

all the best,
Mathias

**Comment by ctag-fh-kiel** [comment]
Implemented with 0.9.16
