### ISSUE TITLE
No output 

### ISSUE THREAD

**Issue by machinehistories** [ctag-fh-kiel/ctag-tbd#29]
I’m not sure if this question should be asked here or not but I get no output from the tbd. The lights work, the buttons work, and I can connect to the webui but it doesn’t output any voltage. The input sound can be faintly heard but the module isn’t generating any output. Do you have any ideas or suggestions. I’ve tried the module in multiple cases but still no output.

**Comment by ctag-fh-kiel** [comment]
are these DIY build issues? Did you use the latest release Firmware (NOT the one in the bin directory of the Master branch?)...

**Comment by ctag-fh-kiel** [comment]
This is the latest release firmware https://github.com/ctag-fh-kiel/ctag-tbd/releases/tag/0.9.18a

**Comment by gr34tmedia** [comment]
> are these DIY build issues? Did you use the latest release Firmware (NOT the one in the bin directory of the Master branch?)...

I ordered mine from instrumentsofthings and i did use the latest firmware you linked above.

**Comment by ctag-fh-kiel** [comment]
The 0.9.18a firmware has been tested. Did the module work before you re-flashed it? Or has it been always non-functional?

Please select e.g. the TB03 plugin on CH0, check if there is any sound coming when you press trig 0. The LED should shine red as well. If you go into the configuration section, you can adjust the output level of the module (58 is the default setting for modular). You have to make sure you select a plugin which actually generates sound (possibly based on trigger), effects need an input signal. You can adjust the input signal level with the two gain pots.

If this doesn't solve your problem, please contact the instruments of things support directly.

**Comment by machinehistories** [comment]
I tried it as you suggested but there is still no output. I am guessing whatever component is handling the -12v is defunct. The +12 is properly powering the 3.3v regulator and the esp32 is working fine as are all the buttons and leds but anything involving negative voltage has stopped working. I will contact instrument of things and see what they have to say. This was a new module and not a kit. If you have any thoughts about what to look at in the circuit I'd be happy to hear them. Otherwise thanks very much for your suggestions and I hope to be using your code soon.
