### ISSUE TITLE
Sound generator not showing up in tbd-sim

### ISSUE THREAD

**Issue by hampa** [ctag-fh-kiel/ctag-tbd#4]
I'm trying to compile a new SoundProcessor.

It successfully shows up in gen_include/ctagSoundProcessorFactory.hpp and tbd-sim builds fine. A "strings tbd-sim" also reveals that the module is compiled into it.

When I go to the web interface it doesn't show up in the list of modules. Anything I need to do to make it show up there?

**Comment by ctag-fh-kiel** [comment]
Hi there, this is problably the spiffs_image/data/spm-config.jsn file, it needs to be reset to initial state. Sound processors are populated only once, if the file was in initial state. 
This is also mentioned in the instructions of the generator (see Important):
https://github.com/ctag-fh-kiel/ctag-tbd/blob/master/generators/readme.md
This behaviour should probably be changed as it confuses a bit... 
Let me know if this was your issue... Thx

**Comment by hampa** [comment]
Yes, that was it :)

Thanks
