### ISSUE TITLE
Feature Request: Loading and Saving Favourites to Json

### ISSUE THREAD

**Issue by careck** [ctag-fh-kiel/ctag-tbd#42]
It would be really useful if the data of a favourite could be stored to and loaded from a json file.

This feature would enable people to share their plugin settings with others. This is similar to the system backup, but instead of storing the settings of all plugins it would only store the settings of the plugins in the favourite.

The UI could change like this:
![image](https://user-images.githubusercontent.com/487856/136646232-c1de32b0-9116-4694-80b2-c8b0b82f3006.png)

**Comment by ctag-fh-kiel** [comment]
Implemented with 708a46d
