### ISSUE TITLE
HVCC support

### ISSUE THREAD

**Issue by dromer** [ctag-fh-kiel/ctag-tbd#53]
Hey there,

I'm running a new maintained fork of the Heavy Compiler Collection over here: https://github.com/Wasted-Audio/hvcc
(HVCC is used on OWL and Daisy modular platforms)

There seems to be some overlap between your project and https://github.com/sinneb/esp32-hvcc
Perhaps you'd like to work on a colab to have HVCC running on your esp32 board?

Any ideas/comments about this?

**Comment by ctag-fh-kiel** [comment]
Hi there, 

Thanks for reaching out! 

It would be awesome to create HVCC support for TBD. In principle, HVCC would need to generate C++ Code deriving from ctagSoundProcessor and implementing the Process() method (https://github.com/ctag-fh-kiel/ctag-tbd/blob/master/components/ctagSoundProcessor/ctagSoundProcessor.hpp).
Furthermore a parameter description json file would need to be generated by HVCC, defining all exposed user parameters of the audio algorithm, examples are:
https://github.com/ctag-fh-kiel/ctag-tbd/blob/master/spiffs_image/data/sp/mui-SimpleVCA.jsn (parameter description)
https://github.com/ctag-fh-kiel/ctag-tbd/blob/master/spiffs_image/data/sp/mp-SimpleVCA.jsn (patch data)

I'd be very happy to support this effort :)
In the past we'd though to add similar support for Faust and VULT, but so far nothing serious has happened in that direction...

**Comment by sinneb** [comment]
Hi all, two years back I did some exploratory work and got HVCC running on ESP32 with some nice performance. Yesterday I decided to pick to the project back up and @smutax pointed me towards this project. Awesome work, I'm looking into possibilities to hook up and start on HVCC.

**Comment by ctag-fh-kiel** [comment]
Great, Thanks for reaching out! Would be awesome to have this available for
ESP32/TBD plugin development...

**Comment by dromer** [comment]
:(
