### ISSUE TITLE
Flash read error

### ISSUE THREAD

**Issue by polymer81** [ctag-fh-kiel/ctag-tbd#57]
I have an ESP32 Wrover module that is 4 MB. Wondering if I need a 16 MB module to use this firmware or if error is caused by something else (it programs fine). 

rst:0x10 (RTCWDT_RTC_RESET),boot:0x1b (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x1b (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x1b (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x1b (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

**Comment by ctag-fh-kiel** [comment]
Yes, you must use the 16MB module due to Wifi OTA firmware update
implementation. Otherwise, you have to modify the firmware to fit the
module.

**Comment by polymer81** [comment]
Ok good to know, thanks.
