### ISSUE TITLE
Favourites getting lost during save-process

### ISSUE THREAD

**Issue by Visuelle-Musik** [ctag-fh-kiel/ctag-tbd#59]
A AEM TBD user reported problems when saving favourites for the TBD here:
https://forum.aemodular.com/thread/2040/tbd-troubleshooting

Seemingly all the changes went lost after save, so it can be suspected that the TBD did a fallback towards the last stable version of the filesystem, but this is not entirely clear.

One more hint is given here as well:
_"I think editting the names/parameters of already stored presets when recalled is what annoyed it. I could test that, though I might not for obvious reasons!"_

And now tIB also added a more detailed description of the steps taken which should help to track down the bug:
_"I think what I did that confused it was editting the text in patches that were already stored as favourites - I'd recall a favourite, go in to the edit window, add text (to be displayed on the module) and then snap it to the same slot, which resulted in them all marked as void in the module - of the ten stored patches, only two survived, and I suspect they were the two I hadn't editted the text on in the way described above."_

**Comment by ctag-fh-kiel** [comment]
Should be fixed with 1.0.0
